const FETCH_REVIEWS_BY_PRODUCT_ID = 'FETCH_REVIEWS_BY_PRODUCT_ID';
const SET_REVIEWS_BY_PRODUCT_ID = 'SET_REVIEWS_BY_PRODUCT_ID';
const SET_ERROR = 'SET_ERROR';

export default {
  FETCH_REVIEWS_BY_PRODUCT_ID,
  SET_REVIEWS_BY_PRODUCT_ID,
  SET_ERROR
}