const FETCH_FEATURED_PRODUCTS = 'FETCH_FEATURED_PRODUCTS';
const SET_FEATURED_PRODUCTS = 'SET_FEATURED_PRODUCTS'; 
const SET_ERROR = 'SET_ERROR';

export default {
  FETCH_FEATURED_PRODUCTS,
  SET_FEATURED_PRODUCTS,
  SET_ERROR
};